LabCourse/mylab_tutor/urls.py
from django.urls import path

from .views import (
    students,
    tutor_help,
    accept_report,
    add_appointment,
    edit_appointment,
    remove_appointment,
    close_appointment,
    remove_appointment_request,
    process_appointment_request,
    update_instructions,
    experiment,
)

urlpatterns = [
    path("students/", students, name="mylab.tutor.students"),
    path("help/", tutor_help, name="mylab.tutor.help"),
    path("request/<int:request_id>/remove", remove_appointment_request, name="mylab.tutor.remove_appointment_request"),
    path(
        "request/<str:experiment_code>/<str:date_str>",
        process_appointment_request,
        name="mylab.tutor.process_appointment_request",
    ),
    path("appointment/", add_appointment, name="mylab.tutor.add_appointment"),
    path("appointment/<int:appointment_id>/edit", edit_appointment, name="mylab.tutor.edit_appointment"),
    path("appointment/<int:appointment_id>/remove", remove_appointment, name="mylab.tutor.remove_appointment"),
    path("appointment/<int:appointment_id>/close", close_appointment, name="mylab.tutor.close_appointment"),
    path("report/<int:report_id>/process", accept_report, name="mylab.tutor.accept_report"),
    path("instructions/upload", update_instructions, name="mylab.tutor.instructions.update"),
    path("experiments/<str:category>/<str:experiment>/", experiment, name="mylab.tutor.experiment"),
]

LabCourse/urls.py
from django.contrib import admin
from django.contrib.auth.views import PasswordChangeView, LoginView, LogoutView
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "accounts/login/",
        LoginView.as_view(template_name="registration/login.html"),
        name="login",
    ),
    # path("accounts/logout/", LogoutView.as_view(), name="logout"),
    path("", include("LabCourse.frontend.urls")),
    path("api/", include("LabCourse.api.urls")),
    path("openid/", include("LabCourse.openid.urls")),
]

LabCourse/mylab_tutor/models.py
from django.db import models

# Create your models here.

LabCourse/mylab_tutor/forms.py
from typing import List, Tuple, Optional
from django import forms
from django.core.exceptions import ValidationError
from django.template.defaultfilters import filesizeformat
from django.utils.deconstruct import deconstructible

from LabCourse.api.models import SemesterDate, AppointmentRequest, Semester, LabUser
from LabCourse.mylab_tutor.utils import FileValidator


class DateInput(forms.DateInput):
    input_type = "date"


class RemoveAppointmentRequestForm(forms.Form):
    checked = forms.BooleanField(label="I really want to remove this request", required=True)


class ProcessAppointmentRequestForm(forms.Form):
    date = forms.ChoiceField(label="Date", required=True)
    newdate = forms.DateField(label="New date", required=False, widget=DateInput)
    students = forms.MultipleChoiceField(label="Students", required=False)
    send_email = forms.BooleanField(label="Send email confirmation", initial=True, required=False)

    def __init__(
        self, *args, requests: List[AppointmentRequest], dates: List[SemesterDate], date: SemesterDate, **kwargs
    ):
        forms.Form.__init__(self, *args, **kwargs)
        self.fields["students"].choices = ((r.student_id, r.student_id) for r in requests)
        self.fields["date"].choices = ((d.pk, d) for d in dates)
        self.fields["date"].initial = date.pk

        # get semester
        self.semester = None if len(dates) == 0 else dates[0].semester

    def clean(self):
        # clean
        super().clean()

        # get date
        newdate = self.cleaned_data.get("newdate")
        if newdate and self.semester:
            # inside semester?
            if newdate < self.semester.start or newdate > self.semester.end:
                raise ValidationError(
                    f"Given date is not within current semester ({self.semester.start} - {self.semester.end})."
                )

            # create or get it
            date, _ = SemesterDate.objects.get_or_create(
                semester=self.semester, date=newdate, defaults={"special": True}
            )

            # set it
            self.cleaned_data["date"] = date.pk


class AddAppointmentForm(forms.Form):
    experiment = forms.ChoiceField(label="Experiment", required=True)
    semester = forms.ChoiceField(label="Semester", required=True)
    date = forms.IntegerField(label="Date", required=True)
    newdate = forms.DateField(label="New date", required=False, widget=DateInput)
    student1 = forms.IntegerField(label="Student 1", required=False)
    student2 = forms.IntegerField(label="Student 2", required=False)
    student3 = forms.IntegerField(label="Student 3", required=False)
    send_email = forms.BooleanField(label="Send email confirmation", initial=True, required=False)

    def __init__(self, *args, experiments, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["experiment"].choices = ((e.code.lower(), f"{e.code} - {e.name}") for e in experiments)
        semesters = Semester.objects.all()
        self.fields["semester"].choices = (
            (s.code, f"{s} ({s.start.strftime('%Y-%m-%d')}-{s.end.strftime('%Y-%m-%d')})") for s in semesters
        )

    def clean(self):
        # clean
        super().clean()

        # get semester
        semester = Semester.objects.get(code=self.cleaned_data["semester"].replace("-", "/"))

        # get date
        newdate = self.cleaned_data.get("newdate")
        if newdate:
            # inside semester?
            if newdate < semester.start or newdate > semester.end:
                raise ValidationError(f"Given date is not within current semester ({semester.start} - {semester.end}).")

            # create or get it
            date, _ = SemesterDate.objects.get_or_create(semester=semester, date=newdate, defaults={"special": True})

            # set it
            self.cleaned_data["date"] = date.pk


class RemoveAppointmentForm(forms.Form):
    checked = forms.BooleanField(label="I really want to remove this appointment", required=True)
    send_email = forms.BooleanField(label="Send email confirmation", initial=True, required=False)


class CloseAppointmentForm(forms.Form):
    students = forms.MultipleChoiceField(label="Students", widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, appointment, **kwargs):
        super().__init__(*args, **kwargs)

        # add students as choices and select them
        self.fields["students"].choices = [(s.pk, s.full_name) for s in appointment.students.all()]
        self.fields["students"].initial = [i for i in appointment.students.all().values_list("id", flat=True)]


class AcceptReportForm(forms.Form):
    tutor = forms.ChoiceField(label="Tutor", required=True)
    passed = forms.ChoiceField(
        label="Result", required=True, choices=[(None, "---"), (True, "Passed"), (False, "Failed")]
    )
    send_email = forms.BooleanField(label="Send email confirmation", initial=True, required=False)

    def __init__(self, *args, appointment, user, **kwargs):
        super().__init__(*args, **kwargs)

        # add all tutors as choices
        tutor_choices = list(appointment.experiment.tutors.all())

        # if current user is admin...
        if user.is_admin:
            # add admin
            tutor_choices += list(LabUser.objects.filter(is_admin=True).all())

            # add all previous tutors
            tutor_choices += list(
                LabUser.objects.filter(tutor_experiments__in=[appointment.experiment]).distinct().all()
            )

        # set unique choices
        tutor_choices = list(set(tutor_choices))
        self.fields["tutor"].choices = [(s.pk, s.full_name) for s in tutor_choices]

        # select current user, if he is one of the choices (should be!)
        if user in tutor_choices:
            self.fields["tutor"].initial = user.pk


class UploadInstructionsForm(forms.Form):
    validate_file = FileValidator(max_size=1024 * 1024 * 10, content_types=("application/pdf",))
    experiment = forms.ChoiceField(label="Experiment")
    instructions = forms.FileField(label="Instructions PDF", required=True, validators=[validate_file])

    def __init__(self, *args, experiments, **kwargs):
        super().__init__(*args, **kwargs)

        # add experiments
        self.fields["experiment"].choices = [(e.pk, f"{e.code} - {e.name}") for e in experiments]

LabCourse/mylab_tutor/templates/mylab_tutor/accept_report.html
{% extends "mylab/base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load report_versions %}
{% load user_link %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor</a></li>
    <li class="breadcrumb-item active">Process report</li>
{% endblock %}

{% block breadcrumb-mobile %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor</a></li>
    <li class="breadcrumb-item active">Process report</li>
{% endblock %}

{% block mylab_content %}
    <h2>My Lab</h2>
    <h3>Accept report</h3>

    {% if success and success is True %}

        <div class="alert alert-success">Report successfully {% if report.passed %}accepted{% else %}rejected{% endif %}.</div>
        <div class="text-center">
            <a href="{% url "mylab" %}" class="btn btn-primary">Back to MyLab</a>
        </div>
        <br/>
        <div class="card card-body bg-light">
            <table class="table table-responsive-sm table-borderless">
                <tr>
                    <th colspan="2">Report {% if report.passed %}passed{% else %}failed{% endif %}</th>
                </tr>
                <tr>
                    <th>Experiment:</th>
                    <td>{% experiment_link report.appointment.experiment True %}</td>
                </tr>
                <tr>
                    <th>Date:</th>
                    <td>{{ report.appointment.date.date|date:"l, j F Y" }}</td>
                </tr>
                <tr>
                    <th>Tutor:</th>
                    <td>{% tutor_link report.tutor fullname=True %}</td>
                </tr>
                <tr>
                    <th>Student:</th>
                    <td>{% user_link report.student fullname=True %}</td>
                </tr>
                <tr>
                    <th>Result:</th>
                    <td>{% if report.passed %}PASSED{% else %}FAILED{% endif %}</td>
                </tr>
            </table>
        </div>

    {% else %}
        <p>
            Here you can accept or reject a lab report from a student. A report should be <strong>good</strong>,
            before you accept it (set "Result" to "passed"). You should give the student a couple of attempts to
            correct the report. Usually <strong>two corrections</strong>, but you can accept more. If the report is
            still not good after that, you can reject it (set "Result" to "failed"). In this case the student will
            have to do an additional lab to pass the Lab Course.
        </p>
        <p>
            Please check carefully that you selected the correct report by examining the name of the
            <strong>experiment</strong>, the <strong>date</strong> and the name of the <strong>student</strong>.
            Then you should also select the <strong>tutor</strong> that actually supervised the lab and will
            receive the credits.
            When you have done that, select whether the student has passed or failed the lab, before clicking
            the button to accept/reject the report.
        </p>
        <hr>
        <form action="{% url "mylab.tutor.accept_report" report.pk %}" method="post">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <div class="mb-3 row">
                <label for="experiment" class="col-sm-3 col-form-label">Experiment:</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control-plaintext" id="experiment"
                           value="{{ report.appointment.experiment.code }} - {{ report.appointment.experiment.name }}">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="date" class="col-sm-3 col-form-label">Date:</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control-plaintext" id="date"
                           value="{{ report.appointment.date.date }}">
                </div>
            </div>
            <hr>
            <div class="mb-3 row">
                <label for="tutor" class="col-sm-3 col-form-label">Tutor:</label>
                <div class="col-sm-9">
                    {% render_field form.tutor class+="form-select" %}
                </div>
            </div>
            <div class="mb-3 row">
                <label for="student" class="col-sm-3 col-form-label">Student:</label>
                <div class="col-sm-9">
                    <input type="text" readonly class="form-control-plaintext" id="student"
                           value="{{ report.student.full_name }}">
                </div>
            </div>
            <hr>
            <div class="mb-3 row">
                <div class="col-sm-3 col-form-label">Report:</div>
                <div class="col-sm-9">
                    {% report_versions report %}
                </div>
            </div>
            <hr>
            <div class="mb-3 row">
                <label for="{{ form.passed.id_for_label }}" class="col-sm-3 col-form-label">Result:</label>
                <div class="col-sm-9">
                    {% render_field form.passed class+="form-select" %}
                </div>
            </div>
            <hr>
            <div {% if not user.is_admin %}class="invisible"{% endif %}>
                <div class="mb-3 row">
                    <div class="col-sm-9 offset-md-3">
                        {% render_field form.send_email %}
                        <label for="{{ form.send_email.id_for_label }}">{{ form.send_email.label }}</label>
                    </div>
                </div>
                <hr>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-success">Accept/reject report</button>
            </div>
        </form>
    {% endif %}

{% endblock %}

LabCourse/mylab_tutor/templates/mylab_tutor/add_appointment.html
{% extends "mylab/base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load user_link %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor</a></li>
    <li class="breadcrumb-item active">Add appointment</li>
{% endblock %}

{% block breadcrumb-mobile %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor</a></li>
    <li class="breadcrumb-item active">Add appointment</li>
{% endblock %}

{% block mylab_content %}
    <h2>My Lab</h2>
    <h3>{% if edit %}Edit{% else %}Add a{% endif %} lab appointment</h3>

    {% if success and success is True %}

        <div class="alert alert-success">Appointment successfully {% if edit %}changed{% else %}created{% endif %}.
        </div>
        <div class="text-center">
            <a href="{% url "mylab" %}" class="btn btn-primary">Back to MyLab</a>
        </div>
        <br/>
        <div class="card card-body bg-light">
            <table class="table table-responsive-sm table-borderless">
                <tr>
                    <th colspan="2">New appointment</th>
                </tr>
                <tr>
                    <th>Experiment:</th>
                    <td>{% experiment_link appointment.experiment True %}</td>
                </tr>
                <tr>
                    <th>Date:</th>
                    <td>{{ appointment.date.date|date:"l, j F Y" }}</td>
                </tr>
                <tr>
                    <th>Student(s):</th>
                    <td>{% user_link_list appointment.students.all fullname=True %}</td>
                </tr>
            </table>
        </div>

    {% else %}
        <p>
            Here you can add/edit an appointment for the <strong>experiments</strong> that you are tutoring. You can
            either pick a <strong>date</strong> from the pre-defined list or create a new one by specifying it in the
            field below. Note that the latter will always be used if given.
        </p>
        <p>
            Finally, you can pick up to three <strong>students</strong> that are participating in the lab. By leaving
            all three to "None", you can use this to block a given date for the experiment.
        </p>
        <hr>
        <form action="
                {% if edit %}{% url "mylab.tutor.edit_appointment" appointment.pk %}{% else %}{% url "mylab.tutor.add_appointment" %}{% endif %}"
              method="post" id="app">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <div class="mb-3 row">
                <label for="{{ form.experiment.id_for_label }}" class="col-sm-3 col-form-label">Experiment:</label>
                <div class="col-sm-9">
                    {% render_field form.experiment class+="form-select" %}
                </div>
            </div>
            <hr>
            <div class="mb-3 row">
                <label for="{{ form.semester.id_for_label }}" class="col-sm-3 col-form-label">Semester:</label>
                <div class="col-sm-9">
                    <select name="semester" id="{{ form.semester.id_for_label }}" class="form-select"
                            v-model="semester">
                        {% for k, v in form.fields.semester.choices %}
                            <option value="{{ k }}" {% if forloop.last %}selected="selected"{% endif %}>{{ v }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="{{ form.date.id_for_label }}" class="col-sm-3 col-form-label">Date:</label>
                <div class="col-sm-9">
                    <select name="date" id="{{ form.date.id_for_label }}" class="form-select" v-model="date">
                        <option v-for="d in dates" :value="d.pk">
                            [[ d.date ]]
                        </option>
                    </select>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="{{ form.newdate.id_for_label }}" class="col-sm-3 col-form-label">New date:</label>
                <div class="col-sm-9">
                    {% render_field form.newdate class+="form-control" %}
                </div>
            </div>
            <hr>
            <div class="mb-3 row">
                <label for="{{ form.student1.id_for_label }}" class="col-sm-3 col-form-label">Student 1:</label>
                <div class="col-sm-9">
                    <select name="student1" id="{{ form.student1.id_for_label }}" class="form-select"
                            v-model="student1">
                        <option value=""></option>
                        <option v-for="s in students" :value="s.pk">
                            [[ s.name ]]
                        </option>
                    </select>
                </div>
            </div>
            <div class="mb-3 row">
                <label for="{{ form.student2.id_for_label }}" class="col-sm-3 col-form-label">Student 2:</label>
                <div class="col-sm-9">
                    <select name="student2" id="{{ form.student2.id_for_label }}" class="form-select"
                            v-model="student2">
                        <option value=""></option>
                        <option v-for="s in students" :value="s.pk">
                            [[ s.name ]]
                        </option>
                    </select>

                </div>
            </div>
            <div class="mb-3 row">
                <label for="{{ form.student3.id_for_label }}" class="col-sm-3 col-form-label">Student 3:</label>
                <div class="col-sm-9">
                    <select name="student3" id="{{ form.student3.id_for_label }}" class="form-select"
                            v-model="student3">
                        <option value=""></option>
                        <option v-for="s in students" :value="s.pk">
                            [[ s.name ]]
                        </option>
                    </select>
                </div>
            </div>
            <hr>
            <div {% if not user.is_admin %}class="invisible"{% endif %}>
                <div class="mb-3 row">
                    <div class="col-sm-9 offset-md-3">
                        {% render_field form.send_email %}
                        <label for="{{ form.send_email.id_for_label }}">{{ form.send_email.label }}</label>
                    </div>
                </div>
                <hr>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-success">{% if edit %}Change{% else %}Add{% endif %} appointment
                </button>
            </div>
        </form>
    {% endif %}

    <script src="{% static 'js/vue.min.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script>
        if ($("#app").length) {
            let semester = $("#id_semester option:selected").attr("value");
            let date = {% if form.initial.date %}{{ form.initial.date }}{% else %}''{% endif %};
            let student1 = {% if form.initial.student1 %}{{ form.initial.student1 }}{% else %}''{% endif %};
            let student2 = {% if form.initial.student2 %}{{ form.initial.student2 }}{% else %}''{% endif %};
            let student3 = {% if form.initial.student3 %}{{ form.initial.student3 }}{% else %}''{% endif %};
            let app = new Vue({
                delimiters: ["[[", "]]"],
                el: '#app',
                data: {
                    semester: '',
                    dates: [],
                    date: '',
                    students: [],
                    student1: '',
                    student2: '',
                    student3: '',
                },
                created: function () {
                    this.semester = semester;
                    this.student1 = student1;
                    this.student2 = student2;
                    this.student3 = student3;
                    this.date = date;
                },
                watch: {
                    semester(newSemester, oldSemester) {
                        let semester = newSemester.replace("/", "-");
                        axios.get("/api/semester/" + semester + "/dates/").then(response => {
                            this.dates = response.data.dates;
                            this.date = this.dates[0].pk;
                        });
                        axios.get("/api/semester/" + semester + "/students/").then(response => {
                            this.students = response.data.students;
                            this.student1 = student1;
                            this.student2 = student2;
                            this.student3 = student3;
                            this.date = date;
                        });
                    }
                }
            });
        }
    </script>
{% endblock %}

LabCourse/mylab_tutor/templates/mylab_tutor/students.html
{% extends "mylab/base.html" %}
{% load static %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor</a></li>
    <li class="breadcrumb-item active">Students</li>
{% endblock %}

{% block breadcrumb-mobile %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor</a></li>
    <li class="breadcrumb-item active">Students</li>
{% endblock %}

{% block mylab_content %}
    <h2>My Lab</h2>
    <h3>Students in {{ semester }}</h3>

    <table class="table table-responsive-sm small">
        <tr>
            <th>Name</th>
            <th>Email</th>
        </tr>
        {% for s in semester.students.all %}
            <tr>
                <td>{{ s.full_name }}</td>
                <td>
                    <icon class="fa fa-envelope"></icon>
                    <a href="mailto:{{ s.email }}">{{ s.email }}</a></td>
            </tr>
        {% endfor %}
    </table>


{% endblock %}

LabCourse/mylab_tutor/templates/mylab_tutor/update_instructions.html
{% extends "mylab/base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor/Examiner</a></li>
    <li class="breadcrumb-item active">Upload instructions</li>
{% endblock %}

{% block breadcrumb-mobile %}
    <li class="breadcrumb-item"><a href="{% url "mylab" %}">My Lab</a></li>
    <li class="breadcrumb-item"><a href="#">Tutor/Examiner</a></li>
    <li class="breadcrumb-item active">Upload instructions</li>
{% endblock %}

{% block mylab_content %}
    <h2>My Lab</h2>
    <h3>Upload instructions</h3>

    {% if success and success is True %}

        <div class="alert alert-success">Instructions successfully uploaded.</div>
        <div class="text-center">
            <a href="{% url "mylab" %}" class="btn btn-primary">Back to MyLab</a>
        </div>

    {% else %}
        <p>
            Here you can upload new instructions for labs for which you are either tutor or examiner. Only PDFs are
            accepted.
        </p>
        <hr>
        <form action="{% url "mylab.tutor.instructions.update" %}" method="post" enctype="multipart/form-data" id="app">
            {% csrf_token %}
            {% if form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
            <div class="mb-3 row">
                <label for="experiment" class="col-sm-3 col-form-label">Experiment:</label>
                <div class="col-sm-9">
                    {% render_field form.experiment class+="form-select" v-model="experiment" %}
                </div>
            </div>
            <hr>
            <div class="mb-3 row">
                <div class="col-sm-3 col-form-label">Previous versions:</div>
                <div class="col-sm-9">
                    <table class="table table-responsive-sm table-striped">
                        <tr>
                            <th>Version</th>
                            <th>Date</th>
                            <th>Uploader</th>
                            <th>File</th>
                            <th>Size</th>
                        </tr>
                        <tr v-if="!instructions">
                            <td colspan="5" class="text-center">Loading...</td>
                        </tr>
                        <tr v-else-if="!instructions.length">
                            <td colspan="5" class="text-center">No instructions found</td>
                        </tr>
                        <tr v-else v-for="i in instructions">
                            <td>[[ i.version ]]</td>
                            <td>[[ i.date ]]</td>
                            <td>[[ i.author ]]</td>
                            <td>
                                <a v-bind:href="i.url">
                                    <icon class="fa fa-file-pdf"></icon>
                                    [[ i.filename ]]
                                </a>
                            </td>
                            <td>[[ i.filesize ]] KiB</td>
                        </tr>

                    </table>
                </div>
            </div>
            <hr>
            <div class="mb-3 row">
                <label for="{{ form.instructions.id_for_label }}" class="col-sm-3 col-form-label">Instructions:</label>
                <div class="col-sm-9">
                    {% render_field form.instructions class+="form-control" accept=".pdf" %}
                    {% for error in form.instructions.errors %}
                        <div class="alert alert-danger m-2">
                            {{ error|escape }}
                        </div>
                    {% endfor %}
                </div>
            </div>
            <hr>
            <div class="text-center">
                <button type="submit" class="btn btn-success">Upload instructions</button>
            </div>
        </form>
    {% endif %}

    <script src="{% static 'js/vue.min.js' %}"></script>
    <script src="{% static 'js/axios.min.js' %}"></script>
    <script>
        if ($("#app").length) {
            let experiment = $("#id_experiment option:selected").attr("value");
            let app = new Vue({
                delimiters: ["[[", "]]"],
                el: '#app',
                data: {
                    experiment: '',
                    instructions: [],
                },
                created: function () {
                    this.experiment = experiment;
                },
                watch: {
                    experiment(newExperiment, oldExperiment) {
                        axios.get("/api/experiment/" + newExperiment + "/instructions/").then(response => {
                            this.instructions = response.data.instructions;
                        });
                    }
                }
            });
        }
    </script>
{% endblock %}